cmake_minimum_required(VERSION 3.28)

# Exercise the real executable without a display, using isolated output files.
file(MAKE_DIRECTORY "${WORK_DIR}")
file(REMOVE "${WORK_DIR}/signal.csv" "${WORK_DIR}/signal.csv.json"
    "${WORK_DIR}/custom.csv" "${WORK_DIR}/custom.csv.json"
    "${WORK_DIR}/signal.iq" "${WORK_DIR}/signal.iq.json"
    "${WORK_DIR}/wgn.csv" "${WORK_DIR}/wgn.csv.json"
    "${WORK_DIR}/awgn.csv" "${WORK_DIR}/awgn.csv.json")
file(REMOVE_RECURSE "${WORK_DIR}/dataset")
function(run expected)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env --unset=DISPLAY --unset=WAYLAND_DISPLAY
        "SPDLOG_LEVEL=off" "${EXECUTABLE}" ${ARGN}
        WORKING_DIRECTORY "${WORK_DIR}" RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(expected STREQUAL "success" AND NOT code STREQUAL "0")
        message(FATAL_ERROR "Command ${ARGN} failed (${code}): ${out}${err}")
    elseif(expected STREQUAL "failure" AND code STREQUAL "0")
        message(FATAL_ERROR "Command ${ARGN} unexpectedly succeeded")
    endif()
    set(last_output "${out}${err}" PARENT_SCOPE)
endfunction()
run(success --help)
if(NOT last_output MATCHES "--gui" OR NOT last_output MATCHES "--log-level"
   OR NOT last_output MATCHES "--modulation" OR NOT last_output MATCHES "batch")
    message(FATAL_ERROR "Help is missing CLI options")
endif()
run(success --version)
run(failure --unknown)
run(failure --log-level invalid)
run(failure --gui --output custom.csv)
run(failure --gui --format cf32)
run(failure --modulation WGN --symbols 10)
run(failure --modulation GFSK)
run(failure --gain 2 batch --output-dir rejected-batch)
run(failure batch --gain 0 --snrs-db 10 --output-dir rejected-batch)
run(failure batch --snrs-db 10 4000 --output-dir rejected-batch)
if(EXISTS "${WORK_DIR}/rejected-batch")
    message(FATAL_ERROR "Invalid batch must be rejected before creating output")
endif()
if(EXISTS "${WORK_DIR}/signal.csv")
    message(FATAL_ERROR "Help/version/invalid arguments must not export files")
endif()
run(success)
file(READ "${WORK_DIR}/signal.csv" csv)
if(NOT csv MATCHES "^time_s,i,q\n")
    message(FATAL_ERROR "Missing CSV header")
endif()
file(READ "${WORK_DIR}/signal.csv.json" metadata)
string(JSON format GET "${metadata}" format)
string(JSON count GET "${metadata}" sample_count)
string(JSON version GET "${metadata}" version)
string(JSON family GET "${metadata}" family)
if(NOT format STREQUAL "csv" OR NOT count EQUAL 2121 OR NOT version EQUAL 2 OR NOT family STREQUAL "linear")
    message(FATAL_ERROR "Unexpected default export metadata")
endif()
file(SHA256 "${WORK_DIR}/signal.csv" original)
run(failure)
file(SHA256 "${WORK_DIR}/signal.csv" preserved)
if(NOT original STREQUAL preserved)
    message(FATAL_ERROR "Failed overwrite modified the original file")
endif()
run(success --overwrite)
run(success --output custom.csv --log-level debug)
if(NOT last_output MATCHES "Generating BPSK signal" OR NOT last_output MATCHES "Exported")
    message(FATAL_ERROR "CLI debug level must override SPDLOG_LEVEL=off")
endif()
file(SHA256 "${WORK_DIR}/custom.csv" custom)
if(NOT original STREQUAL custom)
    message(FATAL_ERROR "Custom output changed deterministic generation")
endif()
run(success --output custom.csv --overwrite --log-level off)
if(NOT last_output STREQUAL "")
    message(FATAL_ERROR "Log level off did not silence output")
endif()
# Binary format uses signal.iq by default.
run(success --format cf32)
file(READ "${WORK_DIR}/signal.iq.json" binary_metadata)
string(JSON binary_format GET "${binary_metadata}" format)
string(JSON binary_count GET "${binary_metadata}" sample_count)
if(NOT binary_format STREQUAL "cf32_le" OR NOT binary_count EQUAL 2121)
    message(FATAL_ERROR "Unexpected binary export metadata")
endif()
file(SIZE "${WORK_DIR}/signal.iq" binary_size)
if(NOT binary_size EQUAL 16968)
    message(FATAL_ERROR "Binary sample size mismatch: ${binary_size}")
endif()
# WGN source produces the configured sample count and noise family metadata.
run(success --modulation wgn --samples 512 --output wgn.csv)
file(READ "${WORK_DIR}/wgn.csv.json" wgn_metadata)
string(JSON wgn_family GET "${wgn_metadata}" family)
string(JSON wgn_count GET "${wgn_metadata}" sample_count)
if(NOT wgn_family STREQUAL "noise" OR NOT wgn_count EQUAL 512)
    message(FATAL_ERROR "Unexpected WGN metadata")
endif()
# AWGN exports must carry parsable noise provenance metadata.
run(success --snr-db 10 --output awgn.csv)
file(READ "${WORK_DIR}/awgn.csv.json" awgn_metadata)
string(JSON awgn GET "${awgn_metadata}" awgn)
string(JSON awgn_snr GET "${awgn_metadata}" awgn requested_snr_db)
string(JSON awgn_interval GET "${awgn_metadata}" awgn reference_interval begin)
if(NOT awgn_snr EQUAL 10 OR NOT awgn_interval EQUAL 80)
    message(FATAL_ERROR "Unexpected AWGN metadata: ${awgn}")
endif()
# Batch sweep writes deterministic frames, sidecars and a manifest.
run(success batch --modulations BPSK WGN --seeds 7 --snrs-db=0,10 --frame-size 64
    --frames-per-point 1 --output-dir dataset)
file(READ "${WORK_DIR}/dataset/manifest.jsonl" manifest)
if(NOT manifest MATCHES "batch_header" OR NOT manifest MATCHES "\"completed\":true")
    message(FATAL_ERROR "Batch manifest is missing its header or completion summary")
endif()
foreach(expected frame_000000_000000.cf32 frame_000000_000000.cf32.json
                 frame_000002_000000.cf32 frame_000002_000000.cf32.json)
    if(NOT EXISTS "${WORK_DIR}/dataset/${expected}")
        message(FATAL_ERROR "Batch output missing ${expected}")
    endif()
endforeach()
file(SIZE "${WORK_DIR}/dataset/frame_000000_000000.cf32" frame_size)
if(NOT frame_size EQUAL 512)
    message(FATAL_ERROR "Batch frame byte size mismatch: ${frame_size}")
endif()
# Frame sidecars and every manifest line must be parsable JSON.
file(READ "${WORK_DIR}/dataset/frame_000000_000000.cf32.json" frame_sidecar)
string(JSON frame_crop GET "${frame_sidecar}" crop offset_samples)
string(JSON frame_snr GET "${frame_sidecar}" axes snr_db)
if(NOT frame_crop EQUAL 120 OR NOT frame_snr EQUAL 0)
    message(FATAL_ERROR "Unexpected batch frame sidecar")
endif()
string(REPLACE "\n" ";" manifest_lines "${manifest}")
foreach(line IN LISTS manifest_lines)
    if(line)
        string(JSON manifest_kind GET "${line}" kind)
        if(NOT manifest_kind MATCHES "^(batch_header|frame|summary)$")
            message(FATAL_ERROR "Unexpected manifest record kind: ${manifest_kind}")
        endif()
    endif()
endforeach()
# Batches never overwrite an existing directory.
run(failure batch --output-dir dataset)
if(NOT HAS_GUI)
    run(failure --gui --log-level error)
    if(NOT last_output MATCHES "GUI support is not included")
        message(FATAL_ERROR "Missing GUI diagnostic")
    endif()
endif()
