include(CheckCXXSourceCompiles)
include(CMakePushCheckState)

set(SIGGEN_SANITIZER "none" CACHE STRING "Project sanitizer: none, address-undefined, or thread")
set_property(CACHE SIGGEN_SANITIZER PROPERTY STRINGS none address-undefined thread)
if(NOT SIGGEN_SANITIZER MATCHES "^(none|address-undefined|thread)$")
    message(FATAL_ERROR "Invalid SIGGEN_SANITIZER='${SIGGEN_SANITIZER}'. Choose none, address-undefined, or thread.")
endif()

# Function scope keeps the probe's language settings out of vendor targets.
function(siggen_check_toolchain)
    set(CMAKE_CXX_STANDARD 23)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    set(CMAKE_CXX_EXTENSIONS OFF)
    set(CMAKE_CXX_SCAN_FOR_MODULES OFF)
    set(CMAKE_TRY_COMPILE_TARGET_TYPE EXECUTABLE)
    cmake_push_check_state(RESET)
    check_cxx_source_compiles("#include <ios>
        int main() { auto mode = std::ios::noreplace; (void)mode; }" SIGGEN_HAS_IOS_NOREPLACE)
    if(NOT SIGGEN_HAS_IOS_NOREPLACE)
        message(FATAL_ERROR "A C++23 compiler and standard library providing std::ios::noreplace are required for I/Q export.")
    endif()
    if(NOT SIGGEN_SANITIZER STREQUAL "none")
        if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux" OR
           NOT CMAKE_CXX_COMPILER_ID MATCHES "^(GNU|Clang)$")
            message(FATAL_ERROR "SIGGEN_SANITIZER=${SIGGEN_SANITIZER} requires Linux with GCC or Clang.")
        endif()
        set(CMAKE_REQUIRED_FLAGS "${SIGGEN_SANITIZER_FLAG} -fno-omit-frame-pointer")
        set(CMAKE_REQUIRED_LINK_OPTIONS "${SIGGEN_SANITIZER_FLAG}")
        check_cxx_source_compiles("int main() { return 0; }" SIGGEN_SUPPORTS_${SIGGEN_SANITIZER})
        if(NOT SIGGEN_SUPPORTS_${SIGGEN_SANITIZER})
            message(FATAL_ERROR "Compiler/linker cannot use SIGGEN_SANITIZER=${SIGGEN_SANITIZER}; install a compatible sanitizer runtime or select none.")
        endif()
    endif()
    cmake_pop_check_state()
endfunction()

if(SIGGEN_SANITIZER STREQUAL "address-undefined")
    set(SIGGEN_SANITIZER_FLAG -fsanitize=address,undefined)
elseif(SIGGEN_SANITIZER STREQUAL "thread")
    set(SIGGEN_SANITIZER_FLAG -fsanitize=thread)
endif()
siggen_check_toolchain()

function(siggen_target_options target)
    target_compile_features(${target} PUBLIC cxx_std_23)
    set_target_properties(${target} PROPERTIES CXX_EXTENSIONS OFF CXX_SCAN_FOR_MODULES OFF)
    if(NOT SIGGEN_SANITIZER STREQUAL "none")
        target_compile_options(${target} PRIVATE ${SIGGEN_SANITIZER_FLAG} -fno-omit-frame-pointer)
        # PUBLIC carries the runtime requirement to consumers of static libraries.
        target_link_options(${target} PUBLIC ${SIGGEN_SANITIZER_FLAG})
    endif()
    if(SIGGEN_ENABLE_WARNINGS)
        if(CMAKE_CXX_COMPILER_ID MATCHES "^(GNU|Clang|AppleClang)$")
            target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
        endif()
    endif()
endfunction()
